/* DO NOT EDIT, file generated by nestjs-i18n */

import { Path } from "nestjs-i18n";
export type I18nTranslations = {
    "errors": {
        "unknown-server-error": string;
        "provide-token": string;
        "provide-valid-token": string;
        "do-not-have-required-role": string;
        "product-key-missing": string;
        "product-key-invalid": string;
        "home-not-found": string;
        "home-is-not-yours": string;
        "email-taken": string;
        "user-not-found": string;
        "incorrect-password": string;
    };
    "messages": {
        "success-signup": string;
        "success-signin": string;
        "product-key-generated": string;
    };
};
export type I18nPath = Path<I18nTranslations>;
